import AccountBalanceIcon from "@mui/icons-material/AccountBalance";
import CardTravelIcon from "@mui/icons-material/CardTravel";
import DirectionsCarIcon from "@mui/icons-material/DirectionsCar";
import ChairIcon from "@mui/icons-material/Chair";
import DiamondIcon from "@mui/icons-material/Diamond";
import CheckroomIcon from "@mui/icons-material/Checkroom";
import DevicesIcon from "@mui/icons-material/Devices";
import FitnessCenterIcon from "@mui/icons-material/FitnessCenter";
import PetsIcon from "@mui/icons-material/Pets";
import BoltIcon from "@mui/icons-material/Bolt";
import BusinessIcon from "@mui/icons-material/Business";
import DirectionsBikeIcon from "@mui/icons-material/DirectionsBike";
import HealingOutlinedIcon from "@mui/icons-material/HealingOutlined";
import MasksOutlinedIcon from "@mui/icons-material/MasksOutlined";
// import {_.random}from 'lodash';

function ActivitieZData() {
  return {
    Data: [
      {
        id: "1",
        activity: "Health & Medical",
        icon: <HealingOutlinedIcon />,
        subCat: [
          {
            id: "11",
            subactivity: "Clinics",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "111",
                businessname: "Lays",
                logo: "",
                adresse: "NewYork city,avenue1234",
                rating: 4,
                overalRating: 4.6,
                reviewsNumber: "2706",
                appreciation: "Good",
                parameters: [
                  "ALL REVIEWS",
                  "CAR",
                  "PROCESS",
                  "EXPERIENCE",
                  "OFFER",
                  "CHECK",
                  "TIME",
                  "HOUR",
                  "TRANSACTION",
                  "COMPANY",
                  "WAY",
                  "CUSTOMER SERVICE",
                  "DEAL",
                  "LOGISTICS",
                  "LOCATION",
                ],
                products: [],
                services: [],
              },
              {
                id: "112",
                businessname: "wayTo Greatness",
                logo: "",
                adresse: "NewYork city,avenue1234",
                rating: 4,
                overalRating: 4.6,
                reviewsNumber: "2706",
                appreciation: "Good",
                parameters: [
                  "ALL REVIEWS",
                  "CAR",
                  "PROCESS",
                  "EXPERIENCE",
                  "OFFER",
                  "CHECK",
                  "TIME",
                  "HOUR",
                  "TRANSACTION",
                  "COMPANY",
                  "WAY",
                  "CUSTOMER SERVICE",
                  "DEAL",
                  "LOGISTICS",
                  "LOCATION",
                ],
                products: [],
                services: [],
              },
              {
                id: "113",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "114",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "115",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "116",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
          {
            id: "12",
            subactivity: "Dental Services",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "121",
                businessname: "comp1x2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "122",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "123",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "124",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "125",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "126",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
          {
            id: "13",
            subactivity: "Diagnostics & Testing",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "131",
                businessname: "comp1xx",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "132",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "133",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "134",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "135",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "136",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
          {
            id: "14",
            subactivity: "Doctors & Surgeons",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "141",
                businessname: "comp1xxx",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "142",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "143",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "144",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "145",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "146",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
          {
            id: "15",
            subactivity: "Health Equipment",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "151",
                businessname: "comp1",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "152",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "153",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "154",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "155",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "156",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
          {
            id: "16",
            subactivity: "Hospital & Emergency",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "161",
                businessname: "comp1",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "162",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "163",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "164",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "165",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "166",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
        ],
      },
      {
        id: "2",
        activity: "Health & Medical",
        icon: <HealingOutlinedIcon />,
        subCat: [
          {
            id: "21",
            subactivity: "Clinics",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "211",
                businessname: "Lays",
                logo: "",
                adresse: "NewYork city,avenue1234",
                rating: 4,
                overalRating: 4.6,
                reviewsNumber: "2706",
                appreciation: "Good",
                parameters: [
                  "ALL REVIEWS",
                  "CAR",
                  "PROCESS",
                  "EXPERIENCE",
                  "OFFER",
                  "CHECK",
                  "TIME",
                  "HOUR",
                  "TRANSACTION",
                  "COMPANY",
                  "WAY",
                  "CUSTOMER SERVICE",
                  "DEAL",
                  "LOGISTICS",
                  "LOCATION",
                ],
                products: [],
                services: [],
              },
              {
                id: "212",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "213",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "214",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "215",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "216",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
          {
            id: "22",
            subactivity: "Dental Services",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "221",
                businessname: "comp1x2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "222",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "223",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "224",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "225",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "226",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
          {
            id: "23",
            subactivity: "Diagnostics & Testing",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "231",
                businessname: "comp1xx",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "232",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "233",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "234",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "235",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "236",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
          {
            id: "24",
            subactivity: "Doctors & Surgeons",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "241",
                businessname: "comp1xxx",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "242",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "243",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "244",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "245",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "246",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
          {
            id: "25",
            subactivity: "Health Equipment",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "251",
                businessname: "comp1",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "252",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "253",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "254",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "255",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "256",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
          {
            id: "26",
            subactivity: "Hospital & Emergency",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "261",
                businessname: "comp1",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "262",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "263",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "264",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "265",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "266",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
        ],
      },
      {
        id: "3",
        activity: "Health & Medical",
        icon: <HealingOutlinedIcon />,
        subCat: [
          {
            id: "31",
            subactivity: "Clinics",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "311",
                businessname: "Lays",
                logo: "",
                adresse: "NewYork city,avenue1234",
                rating: 4,
                overalRating: 4.6,
                reviewsNumber: "2706",
                appreciation: "Good",
                parameters: [
                  "ALL REVIEWS",
                  "CAR",
                  "PROCESS",
                  "EXPERIENCE",
                  "OFFER",
                  "CHECK",
                  "TIME",
                  "HOUR",
                  "TRANSACTION",
                  "COMPANY",
                  "WAY",
                  "CUSTOMER SERVICE",
                  "DEAL",
                  "LOGISTICS",
                  "LOCATION",
                ],
                products: [],
                services: [],
              },
              {
                id: "312",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "313",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "314",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "315",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "316",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
          {
            id: "32",
            subactivity: "Dental Services",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "321",
                businessname: "comp1x2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "322",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "323",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "324",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "325",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "326",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
          {
            id: "33",
            subactivity: "Diagnostics & Testing",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "331",
                businessname: "comp1xx",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "332",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "333",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "334",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "335",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "336",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
          {
            id: "34",
            subactivity: "Doctors & Surgeons",
            icon: <MasksOutlinedIcon />,
            businesses: [
              {
                id: "341",
                businessname: "comp1xxx",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "342",
                businessname: "comp2",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "343",
                businessname: "comp3",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "344",
                businessname: "comp4",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "345",
                businessname: "comp5",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
              {
                id: "346",
                businessname: "comp6",
                logo: "",
                adresse: "",
                profile: [],
                products: [],
                services: [],
                url: "/",
              },
            ],
          },
        
         
        ],
      },
    ],
  };
}
export default ActivitieZData;
